from langchain_core.callbacks import BaseCallbackHandler
from typing import List, Any, Dict
import time

class StreamHandler(BaseCallbackHandler):
    """
    Custom LangChain callback handler for capturing streamed LLM tokens
    and updating a Streamlit placeholder in real-time.
    """
    def __init__(self, placeholder=None):
        super().__init__()
        self.tokens: List[str] = []
        self.placeholder = placeholder
        self.current_text = ""

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Called when a new token is generated by the LLM."""
        self.tokens.append(token)
        self.current_text += token
        
        # Phase 5: Smoothness delay for better UX
        time.sleep(0.01)
        
        # Update Streamlit placeholder with assistant styling (Phase 3)
        if self.placeholder:
            self.placeholder.markdown(
                f'<div class="msg-assistant">🤖 {self.current_text}▌</div>', 
                unsafe_allow_html=True
            )

    def get_response(self) -> str:
        """Combines all captured tokens into the final response string."""
        return self.current_text if self.current_text else "".join(self.tokens)

    def reset(self) -> None:
        """Resets the token buffer and placeholder text."""
        self.tokens = []
        self.current_text = ""
